---
title: "Cross_validation_type"
author: "Vinoth Aryan Nagabosshanam"
date: "March 23, 2017"
output: pdf_document
---
here now we are going to implement the cross valudation techniques
```{r}
library(ISLR)
library(boot)
# boot is package which we need process cross validation process

#View(Auto)
# we are using Auto dataset 
plot(mpg~horsepower,data=Auto)
# we simple building simple linear regression model
mod_fit<-glm(mpg~horsepower,data=Auto)
summary(mod_fit)

#now we fitting cross validation function to model
cv.glm(Auto,mod_fit)$delta 

##Lets write a simple function to use formula (5.2)
loocv=function(fit){
  h=lm.influence(fit)$h
  mean((residuals(fit)/(1-h))^2)
}

## Now we try it out
loocv(mod_fit)




cv.error=rep(0,5)
degree=1:5
for(d in degree){
  mod_fit=glm(mpg~poly(horsepower,d), data=Auto)
  cv.error[d]=loocv(mod_fit)
}
plot(degree,cv.error,type="b")
```



```{r}
da <- get(load('B:/5.R.Rdata'))
#plot(y~X1+X2,data=da)
# we simple building simple linear regression model
modfit<-glm(y~.,data=da)
summary(modfit)

#now we fitting cross validation function to model
cv.glm(da,modfit)$delta 

##Lets write a simple function to use formula (5.2)
loocv=function(fit){
  h=lm.influence(fit)$h
  mean((residuals(fit)/(1-h))^2)
}

## Now we try it out
loocv(modfit)
matplot(Xy,type="l")
```


## 10-fold CV
```{r}
cv.error10=rep(0,5)
for(d in degree){
  mod_fit=glm(mpg~poly(horsepower,d), data=Auto)
  cv.error10[d]=cv.glm(Auto,mod_fit,K=10)$delta[1]
}
plot(degree,cv.error,type="b")
lines(degree,cv.error10,type="b",col="red")


```



## Bootstrap
## Minimum risk investment 

```{r}
alpha=function(x,y){
  vx=var(x)
  vy=var(y)
  cxy=cov(x,y)
  (vy-cxy)/(vx+vy-2*cxy)
}
alpha(Portfolio$X,Portfolio$Y)

## What is the standard error of alpha?

alpha.fn=function(data, index){
  with(data[index,],alpha(X,Y))
}

alpha.fn(Portfolio,1:100)

set.seed(1)
alpha.fn (Portfolio,sample(1:100,100,replace=TRUE))

boot.out=boot(Portfolio,alpha.fn,R=1000)
boot.out
plot(boot.out)
```

